### ISSUE TITLE
Integrate `bandit` into the unittest and mypy action

### ISSUE THREAD

**Issue by BryceStevenWilley** [SuffolkLITLab/ALActions#13]
https://bandit.readthedocs.io/en/latest/

Runs quickly, and gives IMO okay suggestions (not critical, but also not bad per say). But, it's an easy lift, and good to have. If you don't want them, you can adjust what warnings you want to see in your pyproject.toml, which we essentially already require for mypy.

```toml
[tool.bandit]
exclude_dirs = ["tests", "path/to/file"]
tests = ["B201", "B301"]
skips = ["B101", "B601"]
```

Or to skip everything:

```toml
[tool.bandit]
exclude_dirs=["docassemble"]
```
