### ISSUE TITLE
hall_monitor action is down

### ISSUE THREAD

**Issue by ekressmiller** [SuffolkLITLab/ALActions#23]
realized the hall monitor action stopped running for MLH. Reason appears to be [this](https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/).

@BryceStevenWilley

**Comment by nonprofittechy** [comment]
Thanks for catching this, @ekressmiller ! Should be an easy fix

**Comment by BryceStevenWilley** [comment]
We can definitely bump that `setup-python` action, but I think you have another issue. On https://github.com/mplp/docassemble-maintenance/actions/workflows/run_hall_monitor_mplp.yml, it says that:

> This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs. 

I can't enable it myself, so it must be need admin permissions.

https://docs.github.com/en/actions/using-workflows/disabling-and-enabling-a-workflow#enabling-a-workflow should help you re-enable it.

**Comment by ekressmiller** [comment]
Thank you both! Yeah Bryce I was understanding it as the node thing needed fixed first and then we would need to enable the runs again.

**Comment by nonprofittechy** [comment]
It looks like the trick for getting the action to run indefinitely is to schedule a "keep alive" action to add a commit to the package at least once a month or so.

Here's what ChatGPT suggested:

```
name: Keep Alive Commit
on:
  schedule:
    # Runs at 00:00 on the 1st and 15th of each month
    - cron:  '0 0 1,15 * *'

jobs:
  make_commit:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Make a timestamp file
      run: echo "Last updated on $(date)" > keep_alive.txt

    - name: Commit and push if there are changes
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "GitHub Actions"
        git add keep_alive.txt
        git commit -m "Automated keep-alive commit"
        git push
```
